### ISSUE TITLE
Customer Portal Base

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#108]
Need to create a base for the customer portal and it will be called as `cpanel`

**Comment by abhikchakraborty** [comment]
The base is ready and here is the PR https://github.com/sQcrm/sqcrm/pull/113

The base is as
- The cpanel will be as a subfolder inside the crm installation
- So if the domain of the crm is http://demo.sqcrm.com/ then the cpanel will be as http://http://demo.sqcrm.com/cpanel
- We can not have a different sub-domain for the cpanel now it has to be via the crm installation
- cpanel will have its own config files and include
- Core classes, module classes, theme,Javascript library is included from the base crm
- cpanel will have the same modular structure and would need the `.htaccess` as 
```
DirectoryIndex index.php index.html
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase   /

RewriteRule ^modules/(.*)/(.*)$ /cpanel/module.php?sfmodname=$1&sfaction=$2&%{QUERY_STRING}
RewriteRule ^popups/(.*)$ /cpanel/popup_modal.php?modalname=$1&%{QUERY_STRING}

</IfModule>
```
