### ISSUE TITLE
Detail view tab plugin for Organization to manage cpanel

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#110]
As a customer I would like to have following feature for the cpanel
- If I have more than one contact then I would like to have some visibility control on the data being shown on cpanel across different logins

- I would like to enable/disable some of the modules to be displayed on cpanel

For this we will create a tab plugin for the organization, the plugin will do the following

Once the detail view page for the Account/Organization is visited then on clicking the plugin tab
- It will list out all the contacts for that `Account/Organization` , just firstname, lastname and email for now
- This will also list out list of modules to be shown on the cpanel
- The modules could be enabled and disabled.
- Also by default the data visibility on cpanel will be public i.e. each contact after login to cpanel can see all data across the organization where they belong.
- Should have an option to create a hierarchy so that if the customer wants a hierarchy then it should be done

**Comment by abhikchakraborty** [comment]
The plugin is ready and here is the PR https://github.com/sQcrm/sqcrm/pull/115
One change is needed from the original spec i.e. `data visibility on cpanel will be public` rather is should be each cpanel user (contacts) only can see their own data unless the hierarchy is created.

There some DB changes which are as

```sql
create table cpanel_modules (
 `idcpanel_modules` int NOT NULL AUTO_INCREMENT,
 `idmodule` int,
 PRIMARY KEY (`idcpanel_modules`),
 KEY idmodule_idx(idmodule)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

insert into cpanel_modules 
(idmodule) values (13),(15) ;

create table cpanel_modules_org (
 `idcpanel_modules_org` int NOT NULL AUTO_INCREMENT,
 `idorganization` int,
 `idmodule` int,
 PRIMARY KEY (`idcpanel_modules_org`),
 KEY idorganization_idx(idorganization)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

create table cpanel_user_roles (
 `idcpanel_user_roles` int NOT NULL AUTO_INCREMENT,
 `idorganization` int,
 `idcpanel_user` int,
 `roleid` varchar(100),
 `parentrole` varchar(100),
 PRIMARY KEY (`idcpanel_user_roles`),
 KEY idorganization_idx(idorganization),
 KEY idcpanel_user_idx(idcpanel_user)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 ;
```
