### ISSUE TITLE
Data Display on cpanel

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#112]
The cpanel data for different activated modules should be displayed in accordance with the hierarchy being set for that account/organization from the plugin tab.

Also each data is linked with the note module and hence the contact should be able to add some note on those and use of mention to an user should work as how its now.

On the crm level this should display the notes added by the contact on the note section.

**Comment by abhikchakraborty** [comment]
This is ready for review https://github.com/sQcrm/sqcrm/pull/117

**Comment by abhikchakraborty** [comment]
The DB change associated with this task is 
```
alter table notes add column idcpanel_user int default 0 ;
```
