### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#119]
If `Revenue` or `Analytics` item is selected from the menu then both become active. It should only make the selected item active.

![menu-bug](https://cloud.githubusercontent.com/assets/17164263/14588533/4dc91bac-04e9-11e6-9a37-6ad12ee28f8b.png)

**Comment by abhikchakraborty** [comment]
This is fixed and here is the PR https://github.com/sQcrm/sqcrm/pull/121
