### ISSUE TITLE
Plugin JS messages should be moved to its own location

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#120]
Currently all the plugin JS messages are added under https://github.com/sQcrm/sqcrm/blob/master/plugins/js/i18n_message.js

This is not correct and all plugins should have its own JS messages instead of centralized one so that any upgrade becomes easier

**Comment by abhikchakraborty** [comment]
This is done https://github.com/sQcrm/sqcrm/pull/122
