### ISSUE TITLE
Line item Bug

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#123]
While adding a line items for the Quote, Invoice etc and if item is added with 0 number then the total and grand total becomes 0

![line-item-bug](https://cloud.githubusercontent.com/assets/17164263/14737092/ef14ba00-0897-11e6-96f4-4dcfe0ecaaad.png)

**Comment by abhikchakraborty** [comment]
Here is the fix https://github.com/sQcrm/sqcrm/pull/126
