### ISSUE TITLE
Exploring REST API framework

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#127]
Need to do some research on how to built the rest api for sQcrm.
Explore few REST API frameworks.

**Comment by abhikchakraborty** [comment]
We have done some experimentation with some API frameworks for PHP like laravel and lumen and node.js with express using swagger.

The node.js looks to be promising and we will develop the API using

- node.js
- express framework
- swagger-express
- oauth2 server

as the main tools/libraries
