### ISSUE TITLE
Calendar bulk status change

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#136]
Currently when there are lot of calendar entry available and we want to change the status of the event we have to change the status of the event one by one and this is a bit time consuming.

Need to have the option to change the status of selected items like assigned to change

**Comment by abhikchakraborty** [comment]
This is done and here is the PR https://github.com/sQcrm/sqcrm/pull/140
Also currently to achieve this the changes were needed to be done directly on the Calendar module
and we will need some way to avoid this. Perhaps a good idea would be to extend the plugin feature to be able to add action button on the list view page.
