### ISSUE TITLE
Custom Report :: Prospect win by users

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#137]
The report 
- should generate the prospect win by users and total amount
- should have the detailed data report
- should have the option to filter

**Comment by abhikchakraborty** [comment]
The report is ready and here is the PR https://github.com/sQcrm/sqcrm/pull/139
The report will show the data as

- Bar chart with amount per user name 
- This would check the logged in user and will get all the associated users via hierarchy and groups
- Will list all of them in the graph with the amount
- If some users/groups does not have any amount as close win then it will show as 0
- If any group is found then it will also separately show the group members.
