### ISSUE TITLE
Testing and Small fixes before V-1.3 release

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#142]
Need to make sure to run the tests and do small minor fixes before release.
Here is one such small issue on Activity Pending vs completed UI adjustment needed for the summary report

![ui-fix-activity-pending](https://cloud.githubusercontent.com/assets/17164263/15435990/25e1a7cc-1edd-11e6-86e8-0452eef4b498.png)

**Comment by abhikchakraborty** [comment]
Testing looks good and here is the small fix https://github.com/sQcrm/sqcrm/pull/143
