### ISSUE TITLE
Custom Report :: Revenue Report

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#150]
This would show a graph with 3 filters
- Current month (default)
- Current quarter 
- Current year

When showing the  data it should also show side by side comparison of previous month,quarter or year.

- For month show the dates with the interval 5 days.
- For the quarter the dates interval will be 10 days
- For the year the the dates interval will be 20 days

No need to any additional filter and data.
We will have home page widgets for this.

**Comment by abhikchakraborty** [comment]
The report is done and here are the PR
https://github.com/sQcrm/sqcrm/pull/154
https://github.com/sQcrm/sqcrm/pull/156
