### ISSUE TITLE
Introspect the Data History

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#151]
There are some issues with the Data history like it does not record the history for the `checkbox` items.
Need to check if its failing for other and fix them.

**Comment by abhikchakraborty** [comment]
Found few issues on the Data history. Some of the field types were not getting recorded in the change history for example `Field Type 3` and few more specifically popup selector.
The fix is added and tested. Here is the PR https://github.com/sQcrm/sqcrm/pull/152
