### ISSUE TITLE
Report / Custom Report export options to html5

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#164]
Once the Datatable is upgraded update the export options to use Datatable plugins supporting html5 since flash export options got deprecated. https://datatables.net/extensions/buttons/examples/initialisation/export.html

Connects : https://github.com/sQcrm/sqcrm/issues/161

**Comment by abhikchakraborty** [comment]
Upgraded the export options for the report/custom report
PR: https://github.com/sQcrm/sqcrm/pull/167
