### ISSUE TITLE
Prospect Add/Edit form Style Broken

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#173]
The prospect add/edit form is broken.
![potential-add](https://cloud.githubusercontent.com/assets/17164263/16344948/f22e5a88-3a5c-11e6-943f-2ae0ad0d18ec.png)

**Comment by abhikchakraborty** [comment]
The issue is fixed it was from `Field Type 150` with some extra `div` tag caused the issue.
Here is the PR https://github.com/sQcrm/sqcrm/pull/174

The page now looks like
![prospect-fix](https://cloud.githubusercontent.com/assets/1007245/16345702/03563e44-3a61-11e6-8510-414807bd2b6b.png)
