### ISSUE TITLE
Ability to set the plugin permission

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#175]
Currently there is no permission associated with the plugins, this could be accessed by any user who has the respective module view permission.
We may need to define some permission for plugin access, which is very important since we may not want some plugins could be accessed by some users and should be accessed only by designated users.
For example the `Customer Support Permission` plugin is an important plugin and may be good to have some access control.

The plugin permission section 
- should be added in the setting page on plugin activate/deactivate page
- should display the `set permission` option once activated.
- should open a popup on clicking `set permission` button.
- should have option to select existing `role` or `users` for the access permission.
- should not be visible any activated plugin unless permission is set other than the admin login
- should clean up the permissions set once deactivating the plugin.

**Comment by abhikchakraborty** [comment]
The permission for the plugin is implemented and here is the PR https://github.com/sQcrm/sqcrm/pull/183
