### ISSUE TITLE
Send With Us Plugin

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#176]
We currently do not have some marketing module which could be used to send bulk marketing emails.
We have only certain email sending features which is very limited to certain operation, but nothing related to marketing or campaign.

We do not have any plan to have such modules within the crm to send marketing emails via the crm.
There are very powerful marketing tools available and we will utilize those by creating the plugin.
As a first step we will create a plugin for the `Send With Us`

There will be 2 plugins or if possible manage with one plugin to display on both list and detail

- list view plugin
- detail view plugin

The list view plugin will allow users to add email ids to a given group or create a new and add the email along with some other information. The emails could later be used for marketing purpose.

The detail view plugin will show some detail about the email id from send with us along with the log like if the email has been opened, bounced etc.

Will create separate task for each

**Comment by abhikchakraborty** [comment]
This task is done since the related 2 tasks are completed and merged.
