### ISSUE TITLE
Send with us detail view plugin

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#178]
This plugin
- should show the details of the email id if its added to `send with us`, with an option to delete via the api
- should provide the log about the email id i.e. if the email is opened etc https://www.sendwithus.com/docs/api#logs

#176

**Comment by abhikchakraborty** [comment]
The detail view plugin is also ready for the review, the single plugin will serve both list and detail view plugin section. Here is the PR https://github.com/sQcrm/sqcrm/pull/187
