### ISSUE TITLE
Update plugin core to support multiple plugin 

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#179]
Upgrade the plugin core so that same plugin could be served for different types.
We already have the base for that which is, the plugin type is accepted as an array and we can set multiple types. Now need to figure out how to handle multiple at a time along with the position specification.

**Comment by abhikchakraborty** [comment]
The changes in plugin core is done to allow the same plugin to be shown in different available positions. The same plugin could be used for different types which was already there.
The PR is https://github.com/sQcrm/sqcrm/pull/184
Also did the changes on the existing plugin to use the new functions.
