### ISSUE TITLE
Setup wizard

### ISSUE THREAD

**Issue by mattdeveluk** [sQcrm/sqcrm#180]
Setup wizard would be pretty awesome.

**Comment by mattdeveluk** [comment]
Also it would be great to mirgate from Bootstrap 2 to at least Boostrap 3.

**Comment by abhikchakraborty** [comment]
@mattdeveluk thanks for the feedback, could you please provide some more information on `Wizrd Setup` BDD part ? Is that there should be some setting page where we could enable/disable the Wizrds ? If yes then it should be simple to implement and we can add that in the next release https://github.com/sQcrm/sqcrm/milestones/Version%201.6

For the bootstrap upgrade, yes we have already thought about it, and we will definitely work on it, probably after V-1.6.

**Comment by abhikchakraborty** [comment]
Hey @mattdeveluk did you get a chance to look at our new milestone https://github.com/sQcrm/sqcrm/milestone/14 ? We are upgrading everything to bootstrap3x and once stable version of 4x is released we will do the upgrade.

**Comment by abhikchakraborty** [comment]
Closing this task, the bootstrap is upgraded and we will work on the home page widget set up next
