### ISSUE TITLE
Calendar add/edit page css broken

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#181]
Calendar add/edit page CSS broken and the right panel is coming down to the left side even with the larger screen

![calendar-add-edit](https://cloud.githubusercontent.com/assets/17164263/16388700/e562d6b4-3cb7-11e6-904a-2703b1120055.png)

**Comment by abhikchakraborty** [comment]
This is fixed here is the PR https://github.com/sQcrm/sqcrm/pull/182
