### ISSUE TITLE
Listview plugin type does not show on setting page

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#188]
Listview plugin type is not showing the setting page for plugin activation/deavtivation page.
For multi type plugin it should show the multiple names on the setting page. Here is the screen shot how it looks now.
![plugin-bug](https://cloud.githubusercontent.com/assets/17164263/17084509/0ec08eb8-51dd-11e6-988c-4b1141b7a177.png)

**Comment by abhikchakraborty** [comment]
This is fixed and here is the PR https://github.com/sQcrm/sqcrm/pull/189
