### ISSUE TITLE
Upgrade Add/Edit pages

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#197]
Upgrade the different non-admin module add/edit pages with the new CSS

**Comment by abhikchakraborty** [comment]
Here is the PR for the add/edit page changes with CSS https://github.com/sQcrm/sqcrm/pull/202
Few things need to be taken care in different tasks
- Queue module add/edit/delete are done via detail page and needs to be taken care
- Setting page for users listing and add/edit needs to be taken care.
