### ISSUE TITLE
Missing new CSS for some pages

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#216]
Some of the pages are still using the old css class here are the examples

https://github.com/sQcrm/sqcrm/blob/master/module.php
https://github.com/sQcrm/sqcrm/blob/master/plugins.php
https://github.com/sQcrm/sqcrm/blob/master/popup_modal.php
https://github.com/sQcrm/sqcrm/blob/master/widgets.php

Here the alert box is still using the old css `error` this should be `danger` 
Need to make sure to do an audit on these pages and fix the css.

**Comment by abhikchakraborty** [comment]
The CSS has been fixed on the front controllers ! Here is the PR https://github.com/sQcrm/sqcrm/pull/217
