### ISSUE TITLE
Amount field type display issue

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#222]
The amount field type i.e. `field type 30` does not display the currency symbol properly. It should be displayed in alignment with the text field. 
CSS class `input-group` could be used for the alignment.

Here is how it shows now - 
![amount-field-type](https://cloud.githubusercontent.com/assets/17164263/18609338/3f18a346-7d1d-11e6-9cb4-d7d7d71508d4.png)

**Comment by abhikchakraborty** [comment]
The CSS fix is done and here is the PR https://github.com/sQcrm/sqcrm/pull/223
