### ISSUE TITLE
Website table structure

### ISSUE THREAD

**Issue by vivekshekar** [sQcrm/sqcrm#230]
While converting leads to contacts, I found two fatal error on my local, 
Which was for the below fields from the table organisation, 

```
Website
Phone
```

for both the field in the table structure the default was none. Which pdo was breaking because of it. 
Have updated my local table structure with default as null and worked. 

We need to change the structure for organisation table for the above two fields.

**Comment by abhikchakraborty** [comment]
The table definition is fixed. Here is the PR https://github.com/sQcrm/sqcrm/pull/231

**Comment by sQcrm** [comment]
@vivekshekar feel free to close the issue. The table definition is fixed.

**Comment by vivekshekar** [comment]
@abhikchakraborty Done.
