### ISSUE TITLE
Create Project module list view

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#236]
Create the list view considering
- Permission from the CRM
- Overwrite the permission so that only creator and the associated users can see the data
- List view can not have the delete option instead close option
- The close option should be available only to the owner of the project and the permission is `delete` from the CRM privileges.

Sub-task of https://github.com/sQcrm/sqcrm/issues/233

**Comment by abhikchakraborty** [comment]
List view implementation is done and here is the PR https://github.com/sQcrm/sqcrm/pull/242
In addition a fix was done on the datahistory field add/edit on setting page.
