### ISSUE TITLE
Create detail page of the project

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#238]
The detail page of the project will have
- Detail of the project
- Will have a link on the top for tasks
- Will have an option to add new task
- Will have option to add more users into the project
- Should have history page
- Should have Note section like other modules
- Should have option to set the project permission as tab page.

Sub-task of https://github.com/sQcrm/sqcrm/issues/233

**Comment by abhikchakraborty** [comment]
The detail page for the project is completed, There are small changes from the original specification and the things which are done as
- Detail view page
- Right block section to list and add new task depending on the permission on the project
- Right block section for project member depending on the permission
- Adding/removing project members along with email implementation
- Invitation page to accept/reject invitation to join the project and then email to the sender
- Project permission tab to set additional permission for the project
- In addition one bug was fixed which is not able to save the datahistory field information from the setting page while a different module is selected other than the default which is shown on load
- Made some changes on the DataHistory so as to allow custom history, for example when some one is added/ removed/ or rejects project invitation it will be displayed in the history section.

Project Task is not yet implemented and will be implemented on the designated task.

Here is the PR  https://github.com/sQcrm/sqcrm/pull/245

**Comment by abhikchakraborty** [comment]
Here is the changes related to PR https://github.com/sQcrm/sqcrm/pull/245/commits/3c5367c1c81f6467c2697129cda1080d8a4f01e0

The DB changes and new tables created are as 

```sql
create table `project_members`(
  `idproject_members` int NOT NULL auto_increment,
  `idproject` int,
  `iduser` int,
  `sender` int,
  `accepted` tinyint(1) default 0,
  PRIMARY KEY (`idproject_members`),
  KEY `idproject_idx`(`idproject`),
  KEY `iduser_idx`(`iduser`),
  KEY `accepted_idx`(`accepted`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


create table `project_permission`(
 idproject_permission int NOT NULL auto_increment,
 idproject int,
 task_create tinyint(1),
 task_edit tinyint(1),
 task_close tinyint(1),
 task_assignees tinyint(1),
 project_members tinyint(1),
 permission_changer TEXT,
 PRIMARY KEY (`idproject_permission`),
 KEY `idproject_idx`(`idproject`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


insert into emailtemplate (`subject`,`bodyhtml`,`name`,`sendername`,`senderemail`,`language`,`iduser`)
values
(
'{sQcrm} [sender_firstname] [sender_lastname] has invited you to join [project_name]',
'[firstname],<br />
[sender_firstname] [sender_lastname] has invited you to join <b>[project_name]</b>. <br />
Please <a href="[activation_url]">click here</a> to accept the invitation.<br />
If the above link does not work please copy and paste the following url on browser.<br />
[activation_url]<br /><br />
[CRM_NAME]
',
'project_invitation',
'sQcrm.com',
'donot_reply@sQcrm.com',
'en_US',
1
);


insert into emailtemplate (`subject`,`bodyhtml`,`name`,`sendername`,`senderemail`,`language`,`iduser`)
values
(
'{sQcrm} [firstname] [lastname] has accepted the invitation to join [project_name]',
'[sender_firstname],<br />
[firstname] [lastname] has accepted your invitation to join <b>[project_name]</b>. <br /><br />
[CRM_NAME]
',
'project_invitation_accepted',
'sQcrm.com',
'donot_reply@sQcrm.com',
'en_US',
1
);

insert into emailtemplate (`subject`,`bodyhtml`,`name`,`sendername`,`senderemail`,`language`,`iduser`)
values
(
'{sQcrm} [firstname] [lastname] has rejected the invitation to join [project_name]',
'[sender_firstname],<br />
[firstname] [lastname] has rejected your invitation to join <b>[project_name]</b>. <br /><br />
[CRM_NAME]
',
'project_invitation_rejected',
'sQcrm.com',
'donot_reply@sQcrm.com',
'en_US',
1
);

insert into emailtemplate (`subject`,`bodyhtml`,`name`,`sendername`,`senderemail`,`language`,`iduser`)
values
(
'{sQcrm} [firstname] [lastname] your access has been revoked from [project_name]',
'[sender_firstname],<br />
[firstname] [lastname] your access to the project <b>[project_name] has been revoked.</b>. <br />
You can still access other projects where you are a member of or projects created by you.<br /><br />
[CRM_NAME]
',
'project_revoke_access',
'sQcrm.com',
'donot_reply@sQcrm.com',
'en_US',
1
);
```
