### ISSUE TITLE
Create the list view page for project task

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#240]
- The list view page link should be available on project detail page
-  The list view page will load all the tasks associated with the project
- Should have multiple close option for the tasks
- Should have a add option of the task
- After add it will land up in the task detail page
- Should have edit option for the task in list view.

Sub-task of https://github.com/sQcrm/sqcrm/issues/234

**Comment by abhikchakraborty** [comment]
This has been implemented however the `edit option` was not provided, but multiple record update options for `due date` and `priority`

https://github.com/sQcrm/sqcrm/pull/248
