### ISSUE TITLE
Adding Sales order

### ISSUE THREAD

**Issue by vivekshekar** [sQcrm/sqcrm#243]
@abhikchakraborty 
Found an fatal error while adding a new entry to sales order. 
Which breaks the code and I found below error on error log

`PHP Fatal error:  Uncaught PDOException: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'discount_value' at row 1 in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Connection.php(985): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Connection.php(692): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO lin...', Array, Array)\n#3 /var/www/sqcrm/class/core/radria/DataObject.class.php(137): Doctrine\\DBAL\\Connection->insert('lineitems', Array)\n#4 /var/www/sqcrm/class/inventory/Lineitems.class.php(69): DataObject->insert('lineitems', Array)\n#5 /var/www/sqcrm/modules/SalesOrder/SalesOrder.class.php(238): Lineitems->add_line_items(14, '1', Array)\n#6 /var/www/sqcrm/class/core/radria/EventControler.class.php(166): SalesOrder->eventAddRecord(Object(EventControler))\n#7 /var/www/sqcrm/class/core/radria/EventControler in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115, referer: http://sqcrm.localhost/modules/SalesOrder/add
`

**Comment by abhikchakraborty** [comment]
Closing this in favor of fix https://github.com/sQcrm/sqcrm/issues/244
