### ISSUE TITLE
Purchase order 

### ISSUE THREAD

**Issue by vivekshekar** [sQcrm/sqcrm#244]
@abhikchakraborty 

Its not letting me add purchase order for me, its giving me below fatal error, 

`PHP Fatal error:  Uncaught PDOException: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'discount_value' at row 1 in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Connection.php(985): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/sqcrm/Doctrine/Doctrine/DBAL/Connection.php(692): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO lin...', Array, Array)\n#3 /var/www/sqcrm/class/core/radria/DataObject.class.php(137): Doctrine\\DBAL\\Connection->insert('lineitems', Array)\n#4 /var/www/sqcrm/class/inventory/Lineitems.class.php(69): DataObject->insert('lineitems', Array)\n#5 /var/www/sqcrm/modules/PurchaseOrder/PurchaseOrder.class.php(230): Lineitems->add_line_items(16, '1', Array)\n#6 /var/www/sqcrm/class/core/radria/EventControler.class.php(166): PurchaseOrder->eventAddRecord(Object(EventControler))\n#7 /var/www/sqcrm/class/core/radria/Event in /var/www/sqcrm/Doctrine/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115, referer: http://sqcrm.localhost/modules/PurchaseOrder/add
`

As well the tax popup on under the price section is not working as expected. The toggle is not working.

**Comment by abhikchakraborty** [comment]
@vivekshekar , I did some testing and it looks good, however the error that you are getting could be of many reason. The primary reason is, in the DB it was trying to save value more that than the datatype defined.

I checked the `lineitems` table and here how it is
```sql
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| idlineitems          | int(11)      | NO   | PRI | NULL    | auto_increment |
| idmodule             | int(11)      | YES  | MUL | NULL    |                |
| recordid             | int(11)      | YES  | MUL | NULL    |                |
| item_type            | varchar(100) | YES  |     | NULL    |                |
| item_name            | varchar(200) | YES  |     | NULL    |                |
| item_value           | int(11)      | YES  |     | 0       |                |
| item_description     | text         | YES  |     | NULL    |                |
| item_quantity        | float(10,3)  | YES  |     | NULL    |                |
| item_price           | float(10,3)  | YES  |     | NULL    |                |
| discount_type        | varchar(100) | YES  |     | NULL    |                |
| discount_value       | float(10,3)  | YES  |     | NULL    |                |
| discounted_amount    | float(10,3)  | YES  |     | NULL    |                |
| tax_values           | varchar(200) | YES  |     | NULL    |                |
| taxed_amount         | float(10,3)  | YES  |     | NULL    |                |
| total_after_discount | float(10,3)  | YES  |     | NULL    |                |
| total_after_tax      | float(10,3)  | YES  |     | NULL    |                |
| net_total            | float(10,3)  | YES  |     | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+

```
Will need to debug the issue.
And one for sure we will need to change all the `float` data type to `decimal`
I will work on that part and will do some debug to replicate the issue that you are facing.

**Comment by vivekshekar** [comment]
Here what comes on debug

```
Array
(
    [idmodule] => 16
    [recordid] => 5
    [item_type] => product
    [item_name] => Ferrari
    [item_value] => 1
    [item_description] => This is test product
    [item_quantity] => 1
    [item_price] => 2244.00
    [discount_type] => 
    [discount_value] => 
    [discounted_amount] => 0
    [tax_values] => 
    [taxed_amount] => 0.00
    [total_after_discount] => 2244.00
    [total_after_tax] => 2244
    [net_total] => 2244.00
)

```
Looks like the column is sending null and its not getting added in DB throwing the error.

**Comment by vivekshekar** [comment]
@abhikchakraborty 

merge request for the fix, 

https://github.com/sQcrm/sqcrm/pull/246
