### ISSUE TITLE
task add page should have a cancel option

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#249]
Currently to add a new task we can reach page either from task listing page or the task detail page as attached 
![task-add](https://cloud.githubusercontent.com/assets/17164263/23565074/43a7b90a-0072-11e7-84a7-44cde7b307fc.png)

There should be a cancel button on the task add page and it should send back to the referrer.

**Comment by abhikchakraborty** [comment]
This is implemented and here is the PR https://github.com/sQcrm/sqcrm/pull/250
