### ISSUE TITLE
Currency symbol not showing on Dashboard graph

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#86]
The currency symbol is not showing on the Dashboard graph.
Here is the screenshot 
![currency-symbol-bug](https://cloud.githubusercontent.com/assets/17164263/12983664/3d2adc66-d110-11e5-97e0-20385f79dfaf.png)

**Comment by abhikchakraborty** [comment]
This is fixed https://github.com/sQcrm/sqcrm/pull/87
