### ISSUE TITLE
Prospect Reports

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#95]
For the built in reports on sQcrm we will have the following for prospects

**1. Funnel stage report by value and volume**
- This report will show the funnel of prospect by volume (amount) and by numbers per status of prospect.

**2. Prospect forecast**
- This will be a forecast of prospect for next 30,60,90 days

We may add more reports in future if needed.

**Comment by abhikchakraborty** [comment]
The reports are ready and here is the PR.
Some changes/improvement were done on the core of the system as well
https://github.com/sQcrm/sqcrm/pull/100
