### ISSUE TITLE
Prospect Close Lost reason

### ISSUE THREAD

**Issue by sQcrm** [sQcrm/sqcrm#96]
This is currently missing and we need to have it.
Once a Lead is converted as `Close Lost` we need to track the following
- Lost reason ( dropdown)
- One of the reason should be `Lost to competitor`
- If lost reason is `Lost to competitor` then a competitor must be selected from a drop down
- The drop-downs should be manage via pick list editor.

**Comment by abhikchakraborty** [comment]
The code changes for this feature done and here is the PR https://github.com/sQcrm/sqcrm/pull/98

These changes require DB changes and here are these -

```sql
--- add a block
insert into block (idmodule,block_label,sequence)
values
(5,'Close Lost Information',2) ;

update block set sequence = 3 where idblock = 15 ;

--- add the fields info in fields table and in potentials table
insert into fields
(field_name,field_label,field_sequence,idblock,table_name,field_type,is_editable,display,idmodule)
values
('lost_reason','Lost Reason','11',37,'potentials',5,0,1,5);

insert into fields
(field_name,field_label,field_sequence,idblock,table_name,field_type,is_editable,display,idmodule)
values
('competitor_name','Competitor Name','12',37,'potentials',5,0,1,5);

alter table potentials add column lost_reason varchar(200) ;

alter table potentials add column competitor_name varchar(200) ;

```
The migration for existing CRM would need explanation on the new field addition part.
